version: '3.9'
services:
  app:
    build: .
    environment:
      - PGHOST=postgres
      - PGUSER=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres
      - PGPORT=5432
    ports:
      - '8080:8080'
    restart: 'unless-stopped'
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    restart: 'unless-stopped'
    volumes:
      - ./src/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
